name: ai-python
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.7
  - pandas
  - numpy
  - jupyterlab
  - matplotlib
  - seaborn
  - pillow
  - scikit-learn
  - keras
  - pytorch
  - torchvision